# Generated by Django 6.0.2 on 2026-02-28 14:36

from django.db import migrations

def create_mock_data(apps, schema_editor):
    User = apps.get_model('blogs', 'User')
    Post = apps.get_model('blogs', 'Post')
    Comment = apps.get_model('blogs', 'Comment')

    users = []
    for i in range(1, 11):
        users.append(User.objects.create(username=f"amogus{i}", email=f"amogus{i}@very.sus"))

    lor_ips = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque euismod vitae sem sed varius. Nunc vitae lorem quis velit iaculis elementum id at arcu. Vestibulum a congue ante. Nullam laoreet tortor sed arcu posuere, non egestas quam suscipit. Sed bibendum ac ante eu commodo. Nulla iaculis tincidunt erat, ut pretium diam pharetra feugiat. Suspendisse ut porta purus. Vivamus interdum, enim et tristique auctor, dolor libero aliquet ipsum, vel tempor quam risus ac mi. In lobortis at neque nec suscipit. Suspendisse suscipit lacinia laoreet. Vestibulum at elit sed sapien cursus dictum sed vitae ipsum."

    post1 = Post.objects.create(
        title="Сбор амогусов1",
        content=lor_ips,
        author=users[0],
    )
    post1.likes.set([users[1], users[4], users[8]])

    Post.objects.create(
        title="Сбор амогусов2",
        content=lor_ips,
        author=users[1],
    )

    post3 = Post.objects.create(
        title="Сбор амогусов3",
        content=lor_ips,
        author=users[2],
    )
    post3.likes.set(users)

    comment1 = Comment.objects.create(
        post=post1,
        author=users[9],
        text="really cool",
    )
    comment1.likes.set([users[0]])


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_mock_data)
    ]
